new commit

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -9,6 +9,7 @@ env:
   APP_IMAGE: ghcr.io/${{ secrets.REPOSITORY_GITHUB }}/text_extract
   NGINX_IMAGE: ghcr.io/${{ secrets.REPOSITORY_GITHUB }}/nginx
   ACME_IMAGE: ghcr.io/${{ secrets.REPOSITORY_GITHUB }}/acme
+  POSTGRES_IMAGE: ghcr.io/${{ secrets.REPOSITORY_GITHUB }}/postgres
   PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
   DIGITAL_OCEAN_IP_ADDRESS: ${{ secrets.DIGITAL_OCEAN_IP_ADDRESS }}
   PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
@@ -16,59 +17,59 @@ env:
 
 jobs:
 
-  test:
-    name: Run Tests
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./work_dir
-
-    env:
-      SECRET_KEY: ${{ secrets.SECRET_KEY }}
-      CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
-      SQL_NAME: ${{ secrets.TEST_DB_NAME }}
-      SQL_USER: ${{ secrets.TEST_DB_USER }}
-      SQL_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
-      SQL_HOST: ${{ secrets.TEST_DB_HOST }}
-      SQL_PORT: ${{ secrets.TEST_DB_PORT }}
-
-    services:
-      postgres:
-        image: postgres:latest
-        env:
-          POSTGRES_USER: ${{ env.SQL_USER }}
-          POSTGRES_PASSWORD: ${{ env.SQL_PASSWORD }}
-          POSTGRES_DB: ${{ env.SQL_NAME }}
-        ports:
-          - 5432:5432
-        options:
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v2
-
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.11
-
-      - name: Install Dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-
-      - name: Run Tests
-        run: |
-          python manage.py test
+#  test:
+#    name: Run Tests
+#    runs-on: ubuntu-latest
+#    defaults:
+#      run:
+#        working-directory: ./work_dir
+#
+#    env:
+#      SECRET_KEY: ${{ secrets.SECRET_KEY }}
+#      CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
+#      SQL_NAME: ${{ secrets.TEST_DB_NAME }}
+#      SQL_USER: ${{ secrets.TEST_DB_USER }}
+#      SQL_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
+#      SQL_HOST: ${{ secrets.TEST_DB_HOST }}
+#      SQL_PORT: ${{ secrets.TEST_DB_PORT }}
+#
+#    services:
+#      postgres:
+#        image: postgres:latest
+#        env:
+#          POSTGRES_USER: ${{ env.SQL_USER }}
+#          POSTGRES_PASSWORD: ${{ env.SQL_PASSWORD }}
+#          POSTGRES_DB: ${{ env.SQL_NAME }}
+#        ports:
+#          - 5432:5432
+#        options:
+#          --health-cmd pg_isready
+#          --health-interval 10s
+#          --health-timeout 5s
+#          --health-retries 5
+#
+#    steps:
+#      - name: Checkout Repository
+#        uses: actions/checkout@v2
+#
+#      - name: Set up Python
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.11
+#
+#      - name: Install Dependencies
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install -r requirements.txt
+#
+#      - name: Run Tests
+#        run: |
+#          python manage.py test
 
   build:
     name: Build Docker Images
     runs-on: ubuntu-latest
-    needs: test
+#    needs: test
 
     steps:
       - name: Checkout master
@@ -100,17 +101,19 @@ jobs:
           echo "APP_IMAGE=$(echo ${{ env.APP_IMAGE }} )" >> $GITHUB_ENV
           echo "ACME_IMAGE=$(echo ${{ env.NGINX_IMAGE }} )" >> $GITHUB_ENV
           echo "NGINX_IMAGE=$(echo ${{ env.ACME_IMAGE }} )" >> $GITHUB_ENV
+          echo "POSTGRES_IMAGE=$(echo ${{ env.POSTGRES_IMAGE }} )" >> $GITHUB_ENV
 
       - name: Log in to GitHub Packages
         run: echo ${PERSONAL_ACCESS_TOKEN} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
         env:
-          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          PERSONAL_ACCESS_TACME_IMAGEOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
       - name: Pull images
         run: |
           docker pull ${{ env.APP_IMAGE }} || true
           docker pull ${{ env.NGINX_IMAGE }} || true
           docker pull ${{ env.ACME_IMAGE }} || true
+          docker pull ${{ env.POSTGRES_IMAGE }} || true
 
       - name: Build images
         run: |
@@ -121,6 +124,7 @@ jobs:
           docker push ${{ env.APP_IMAGE }}
           docker push ${{ env.NGINX_IMAGE }}
           docker push ${{ env.ACME_IMAGE }}
+          docker push ${{ env.POSTGRES_IMAGE }}
 
   deploy:
     name: Copy file to DigitalOcean
@@ -167,27 +171,27 @@ jobs:
           source: "./acme_companion, .env, ./nginx, ./docker-compose.prod.yml"
           target: /home/rodion/TEXT_EXTRACT_PDF
 
-  deploy2:
-      name: Deploy to DigitalOcean
-      runs-on: ubuntu-latest
-      needs: deploy
-
-      steps:
-        - name: executing remote ssh commands using password
-          uses: appleboy/ssh-action@v1.0.0
-          with:
-            host: ${{ env.DIGITAL_OCEAN_IP_ADDRESS }}
-            username: root
-            key: ${{ env.PRIVATE_KEY }}
-            script: |
-              cd /home/rodion/TEXT_EXTRACT_PDF
-              
-              source .env
-              echo ${{ env.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ env.NAMESPACE }} --password-stdin
-              docker pull ghcr.io/rodionmaulenov/textextractpdf/text_extract 
-              docker pull ghcr.io/rodionmaulenov/textextractpdf/nginx 
-              docker pull ghcr.io/rodionmaulenov/textextractpdf/acme 
-              docker-compose -f docker-compose.prod.yml up -d
+#  deploy2:
+#      name: Deploy to DigitalOcean
+#      runs-on: ubuntu-latest
+#      needs: deploy
+#
+#      steps:
+#        - name: executing remote ssh commands using password
+#          uses: appleboy/ssh-action@v1.0.0
+#          with:
+#            host: ${{ env.DIGITAL_OCEAN_IP_ADDRESS }}
+#            username: root
+#            key: ${{ env.PRIVATE_KEY }}
+#            script: |
+#              cd /home/rodion/TEXT_EXTRACT_PDF
+#
+#              source .env
+#              echo ${{ env.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ env.NAMESPACE }} --password-stdin
+#              docker pull ghcr.io/rodionmaulenov/textextractpdf/text_extract
+#              docker pull ghcr.io/rodionmaulenov/textextractpdf/nginx
+#              docker pull ghcr.io/rodionmaulenov/textextractpdf/acme
+#              docker-compose -f docker-compose.prod.yml up -d
 
 
 
